$url = 'http://downloads.ghostscript.com/public/gs909w32.exe'
$url64 = 'http://downloads.ghostscript.com/public/gs909w64.exe'
$uninstallRegKey = 'HKLM:SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\GPL Ghostscript 9.09'
$version = [Version] '9.09'
$package = 'ghostscript.app'